// Generated by CoffeeScript 1.3.1
(function() {
  var Listener, fs, http, io, zmq;

  io = require('socket.io').listen(8001);

  fs = require('fs');

  http = require('http');

  zmq = require('zmq');

  Listener = (function() {

    Listener.name = 'Listener';

    function Listener(name, port, client_socket) {
      this.name = name;
      this.port = port;
      this.client_socket = client_socket;
      this.socket = zmq.socket('sub');
      this.socket.connect('tcp://127.0.0.1:' + this.port.toString());
      this.socket.subscribe('');
    }

    Listener.prototype.run = function() {
      var _this = this;
      return this.socket.on('message', function(msg) {
        _this.data = JSON.parse(msg.toString());
        console.log('Recv msg from ' + _this.data.name);
        console.log(_this.data);
        return _this.client_socket.emit('atesim', _this.data);
      });
    };

    return Listener;

  })();

  /* Main
  */


  console.log('Qikify: View Server');

  io.on('connection', function(client_socket) {
    var ateSimListener;
    ateSimListener = new Listener('atesim', 5001, client_socket);
    client_socket.emit('message', 'Qikify: client has connected');
    console.log('Qikify: client has connected');
    client_socket.on('message', function(msg) {
      return console.log('*** Message received from client: ' + msg);
    });
    return ateSimListener.run();
  });

}).call(this);
