// Generated by CoffeeScript 1.3.1
(function() {
  var Forwarder, fs, http, io, zmq;

  io = require('socket.io').listen(8001);

  fs = require('fs');

  http = require('http');

  zmq = require('zmq');

  Forwarder = (function() {

    Forwarder.name = 'Forwarder';

    function Forwarder(name, port, client_socket) {
      this.name = name;
      this.port = port;
      this.client_socket = client_socket;
      this.socket = zmq.socket('sub');
      this.socket.connect('tcp://127.0.0.1:' + this.port.toString());
      this.socket.subscribe('');
    }

    Forwarder.prototype.run = function() {
      var _this = this;
      return this.socket.on('message', function(msg) {
        _this.data = JSON.parse(msg.toString());
        console.log('Recv msg from ' + _this.data.name);
        console.log(JSON.stringify(_this.data));
        return _this.client_socket.emit('message', _this.data);
      });
    };

    return Forwarder;

  })();

  /* Main
  */


  console.log('Qikify: View Server');

  io.on('connection', function(client_socket) {
    var ateSimForwarder;
    console.log('Qikify: client has connected');
    client_socket.on('message', function(msg) {
      return console.log('*** Message received from client: ' + msg);
    });
    ateSimForwarder = new Forwarder('atesim', 5001, client_socket);
    return ateSimForwarder.run();
  });

}).call(this);
